# Generated by Django 4.1.4 on 2022-12-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="avatar",
            field=models.ImageField(default=None, upload_to="images"),
        ),
        migrations.AddField(
            model_name="employee",
            name="cv",
            field=models.FileField(default=None, upload_to="files"),
        ),
    ]
